name: Deploy Vault Resources

on:
    pull_request:
    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        runs-on: arc-runners
    
        env:
            VAULT_ADDR: http://vault.vault.svc.cluster.local:8200
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Authenticate to Vault
              uses: hashicorp/vault-action@v3
              with:
                url: ${{ env.VAULT_ADDR }}
                method: jwt
                path: jwt
                role: vault-deploy
                secrets: |
                  kubernetes/creds/vault-deploy?kubernetes_namespace=vault kubeconfig | KUBECONFIG_DATA ;
        
            - name: Configure Kubeconfig
              run: |
                mkdir -p $HOME/.kube
                echo "${{ steps.vault.outputs.KUBECONFIG_DATA }}" > $HOME/.kube/config
                chmod 600 $HOME/.kube/config
            
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
            
            - name: Terraform Init
              run: |
                terraform init
            
            - name: Terraform Plan
              run: |
                terraform plan
            
            - name: Terraform Apply
              if: ${{ github.ref_name == github.event.repository.default_branch }}
              run: |
                terraform apply -auto-approve